for(var e=[],f=document.getElementById("runner"),l,m=[!1,!1,!1,!1],n=[],p=Math.max(Math.ceil(m.length/4),2),q=0,r=0,u=[],w=360*Math.random(),x="hsl("+w+", 50%, 50%)",y=0,z=1,A=0,B=0;B<m.length;B++){w=360*Math.random();for(x="hsl("+w+", 50%, 50%)";-1!=u.indexOf(w-w%100)||100<y;)w=360*Math.random(),x="hsl("+w+", 50%, 50%)",y++;y=0;u.push(w-w%100);0==B%4?(q=5,r=f.height/p+z*f.width/p*Math.floor(B/4),r-=r%5):1==B%4?(q=f.width-10,r=f.height/p+z*f.width/p*Math.floor(B/4),r-=r%5):2==B%4?(q=f.width/p+z*f.width/
p*Math.floor(B/4),q-=q%5,r=5):3==B%4&&(q=f.width/p+z*f.width/p*Math.floor(B/4),q-=q%5,r=f.height-10);z=-z;A++;n.push(new C)}l=n;for(var D=[Date.now(),Date.now()],E=[],F=0;15>F;F++)E.push(new G);var G=E,H=!1;
function G(){this.y=this.x=0;this.color="#FF0000";this.b=5;this.D=function(){var a=document.getElementById("runner"),d=Math.random()*(a.width-this.b),g=Math.random()*(a.height-this.b);this.x=d-d%this.b;this.y=g-g%this.b;for(var t=0,k=!0;k&&100>t;){k=!1;for(d=0;d<l.length;d++)l[d].i[this.x,this.y]&&(k=!0);k&&(d=Math.random()*(a.width-this.b),g=Math.random()*(a.height-this.b),this.x=d-d%this.b,this.y=g-g%this.b);t++}};this.w=function(){var a=document.getElementById("runner").getContext("2d");a.fillStyle=
this.color;a.fillRect(this.x,this.y,this.b,this.b);a.stroke()};this.D()}
function C(){var a=q,d=r,g=m[B],t=B+1,k=x;this.u=function(b){return this.C(b[0],b[1])};this.C=function(b,a){return b>=a?b*b+b+a:b+a*a};this.F=function(){var b=[];1==this.g%4?(b[0]=this.b,b[1]=0):2==this.g%4?(b[0]=-this.b,b[1]=0):3==this.g%4?(b[0]=0,b[1]=this.b):0==this.g%4&&(b[0]=0,b[1]=-this.b);return b};this.g=t;this.b=5;this.a=[[a,d]];this.j=[this.u(this.a[0])];this.s=[a,d];this.B=3;this.l=0;this.o=!1;this.c=this.F();this.A=0;this.color=k;this.m=g;this.f=[0,0];this.h=[!1,!1,!1,!1];this.K=function(b){this.l+=
this.B;this.A++;G[b].D()};this.H=function(){for(var b=0;b<G.length;b++)if(this.a[0][0]==G[b].x&&this.a[0][1]==G[b].y)return b;return-1};this.update=function(b,a){this.l+=this.B;if(!this.o){var c=-1;-1!=(c=this.H())&&this.K(c);this.L();for(c=this.a.length-1;0<=c;c--)c==this.a.length-1&&(this.s[0]=this.a[c][0],this.s[1]=this.a[c][1]),0==c?(this.a[c][0]+=this.c[0],this.a[c][1]+=this.c[1]):(this.a[c][0]=this.a[c-1][0],this.a[c][1]=this.a[c-1][1]),this.j[c]=this.u(this.a[c]);0<this.l&&(c=[this.s[0],this.s[1]],
this.a.push(c),this.j[this.a.length-1]=this.u(c),this.l--)}this.I(b,a)};this.L=function(){if(this.m)if(e[87]&&1==this.g||e[38]&&2==this.g){if(1==this.a.length||this.c[1]!=this.b)this.c[0]=0,this.c[1]=-this.b}else if(e[65]&&1==this.g||e[37]&&2==this.g){if(1==this.a.length||this.c[0]!=this.b)this.c[0]=-this.b,this.c[1]=0}else if(e[68]&&1==this.g||e[39]&&2==this.g){if(1==this.a.length||this.c[0]!=-this.b)this.c[0]=this.b,this.c[1]=0}else{if(e[83]&&1==this.g||e[40]&&2==this.g)if(1==this.a.length||this.c[1]!=
-this.b)this.c[0]=0,this.c[1]=this.b}else this.J()};this.i=function(b,a){return-1!=this.j.indexOf(this.C(b,a))?!0:!1};this.v=function(b){for(var a=0;a<l.length;a++)if(this!==l[a]&&(0==b&&l[a].i(this.a[0][0]+this.b,this.a[0][1]+0)||1==b&&l[a].i(this.a[0][0]-this.b,this.a[0][1]+0)||2==b&&l[a].i(this.a[0][0]+0,this.a[0][1]+this.b)||3==b&&l[a].i(this.a[0][0]+0,this.a[0][1]-this.b)))return!0;return!1};this.J=function(){var a=document.getElementById("runner");this.h[0]=this.i(this.a[0][0]+this.b,this.a[0][1]+
0)||this.a[0][0]+this.b>=a.width||this.v(0);this.h[1]=this.i(this.a[0][0]-this.b,this.a[0][1]+0)||0>this.a[0][0]-this.b||this.v(1);this.h[2]=this.i(this.a[0][0]+0,this.a[0][1]+this.b)||this.a[0][1]+this.b>=a.height||this.v(2);this.h[3]=this.i(this.a[0][0]+0,this.a[0][1]-this.b)||0>this.a[0][1]-this.b||this.v(3);a=this.G();if(4==a||-1==a)this.h[0]?this.h[1]?this.h[2]?this.h[3]||(this.c[0]=0,this.c[1]=-this.b):(this.c[0]=0,this.c[1]=this.b):(this.c[0]=-this.b,this.c[1]=0):(this.c[0]=this.b,this.c[1]=
0);else{var h=2!=a&&3!=a?0:2==a?this.b:-this.b;this.c[0]=0!=a&&1!=a?0:0==a?this.b:-this.b;this.c[1]=h}};this.G=function(){var a,h;this.f[0]=2*f.width;this.f[1]=2*f.height;for(var c=0;c<G.length;c++)a=G[c].x-this.a[0][0],h=G[c].y-this.a[0][1],a*a+h*h<this.f[0]*this.f[0]+this.f[1]*this.f[1]&&(this.f[0]=a,this.f[1]=h);return 0<this.f[0]&&!this.h[0]?0:0>this.f[0]&&!this.h[1]?1:0<this.f[1]&&!this.h[2]?2:0>this.f[1]&&!this.h[3]?3:0==this.f[0]&&0==this.f[1]?4:-1};this.reset=function(){this.c=this.F();this.a=
[[a,d]];this.j=[this.u(this.a[0])];this.s=[a,d];this.l=0;this.o=!1};this.I=function(a,h){var b=document.getElementById("runner");if(0==this.a.length||this.a[0][0]+this.b>b.width||0>this.a[0][0]||this.a[0][1]+this.b>b.height||0>this.a[0][1])this.o=!0;else{this.j.sort();for(var b=!1,d=0;d<this.j.length-1;d++)this.j[d]==this.j[d+1]&&(b=!0);for(d=0;d<h.length;d++)if(d!=a&&h[d].i(this.a[0][0],this.a[0][1])){h[d].A++;b=!0;break}(this.o=b?!0:!1)&&console.log("Player "+this.g+" ran into itself and died.")}};
this.w=function(){var a=document.getElementById("runner").getContext("2d");a.fillStyle=this.color;for(var d=0;d<this.a.length;d++)a.fillRect(this.a[d][0],this.a[d][1],this.b,this.b),a.stroke()}}
function I(){f.getContext("2d").clearRect(0,0,f.width,f.height);f.getContext("2d").fillStyle="#000000";f.getContext("2d").fillRect(0,0,f.width,f.height);var a;75<D[1]-D[0]?(D[0]=D[1],a=!0):(D[1]=Date.now(),a=!1);if(a&&!H)for(a=0;a<l.length;a++)l[a].update(a,l);for(a=0;a<l.length;a++)l[a].o&&l[a].reset();for(a=0;a<G.length;a++)G[a].w();for(a=0;a<l.length;a++)l[a].w();H&&(a=f.getContext("2d"),a.font="20px Georgia",a.fillStyle="white",a.fillText("Paused",f.width/2-25,f.height/2-10));a=[];for(var d=[],
g=0;g<l.length;g++)a.push("Player "+(g+1)+": "+l[g].A),d.push(l[g].color);for(var g=f.width-100,t=f.height-100,k=0,b=13*a.length+2*a.length,h=f.getContext("2d"),c=0;c<a.length;c++)k=Math.max(h.measureText(a[c]).width,k);t+b>f.height&&(t=f.height-b);g+k>f.width&&(t=f.width-k);for(c=0;c<a.length;c++){var k=a[c],b=g,h=t+15*c,J=d[c],v=f.getContext("2d");v.save();v.font="bold 13px Arial";v.textAlign="left";v.fillStyle=J;v.lineWidth=2;v.fillText(k,b,h);v.restore()}window.requestAnimationFrame(I)}
window.addEventListener("keydown",function(a){e[a.keyCode]=!0});window.addEventListener("keyup",function(a){e[a.keyCode]=!1});document.getElementById("runner").addEventListener("click",function(){H=!H});document.getElementById("player1").addEventListener("click",function(){0<l.length&&(document.getElementById("player1").innerHTML=l[0].m?"Player 1: AI":"Player 1: Human (WASD)",l[0].m=!l[0].m)});
document.getElementById("player2").addEventListener("click",function(){0<l.length&&(document.getElementById("player2").innerHTML=l[1].m?"Player 2: AI":"Player 2: Human (ARROW KEYS)",l[1].m=!l[1].m)});window.requestAnimationFrame(I);
